services:
  one-gate-payment-db:
    container_name: one-gate-payment-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer123
      POSTGRES_DB: one_gate_payment
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - one_gate_payment_data:/var/lib/postgresql/data

  flyway:
    container_name: flyway
    image: flyway/flyway
    depends_on:
      one-gate-payment-db:
        condition: service_healthy
    volumes:
      - ./migrations:/flyway/sql
    command: |
      -url=jdbc:postgresql://one-gate-payment-db:5432/one_gate_payment -user=developer -password=developer123 migrate

  authentication-one-gate-payment:
    container_name: authentication-one-gate-payment
    restart: always
    depends_on:
      - one-gate-payment-db
      - flyway
    environment:
      PROFILE_MODE: local
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    image: "authentication-one-gate-payment:latest"

  payment-one-gate-payment:
    container_name: payment-one-gate-payment
    restart: always
    depends_on:
      - one-gate-payment-db
      - flyway
      - authentication-one-gate-payment
    environment:
      PROFILE_MODE: local
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    build:
      context: ./
      dockerfile: Dockerfile
    image: "payment-one-gate-payment:latest"

  kong-database:
    container_name: kong-database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kongpass
      POSTGRES_DB: kong
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kong" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - kong_data:/var/lib/postgresql/data

  kong-migration:
    container_name: kong-migration
    image: kong/kong-gateway:latest
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PORT: 5432
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PG_DATABASE: kong
    command: kong migrations bootstrap

  one-gate-payment-gateway:
    container_name: one-gate-payment-gateway
    image: kong/kong-gateway:latest
    restart: always
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PORT: 5432
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_ADMIN_GUI_URL: http://localhost:8002
      # Enable plugins
      KONG_PLUGINS: bundled,jwt,key-auth,rate-limiting,cors
    ports:
      - "8000:8000"    # Kong Proxy
      - "8001:8001"    # Kong Admin API
      - "8002:8002"    # Kong Manager (GUI)
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 30s
      timeout: 30s
      retries: 3

  kong-config:
    container_name: kong-config
    image: curlimages/curl:latest
    depends_on:
      one-gate-payment-gateway:
        condition: service_healthy
    volumes:
      - ./kong-config.sh:/kong-config.sh
    command: sh /kong-config.sh

volumes:
  one_gate_payment_data:
  kong_data: