apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment-service1
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
